"""create mvp schema

Revision ID: 6316720c4c8c
Revises:
Create Date: 2026-05-02 20:49:22.270866+00:00

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "6316720c4c8c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employees",
        sa.Column("employee_code", sa.String(length=32), nullable=False),
        sa.Column("full_name", sa.String(length=160), nullable=False),
        sa.Column("phone", sa.String(length=40), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("emergency_contact_name", sa.String(length=160), nullable=True),
        sa.Column("emergency_contact_phone", sa.String(length=40), nullable=True),
        sa.Column("department", sa.String(length=80), nullable=True),
        sa.Column("job_title", sa.String(length=120), nullable=True),
        sa.Column("wage_type", sa.String(length=40), nullable=True),
        sa.Column("wage_rate_npr", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=24), server_default="active", nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status in ('active', 'inactive', 'probation')",
            name=op.f("ck_employees_employee_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employees")),
        sa.UniqueConstraint("employee_code", name=op.f("uq_employees_employee_code")),
    )
    op.create_index(
        "ix_employees_status_department", "employees", ["status", "department"], unique=False
    )
    op.create_table(
        "permissions",
        sa.Column("code", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permissions")),
        sa.UniqueConstraint("code", name=op.f("uq_permissions_code")),
    )
    op.create_table(
        "product_styles",
        sa.Column("style_code", sa.String(length=48), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=False),
        sa.Column("sample_status", sa.String(length=40), server_default="draft", nullable=False),
        sa.Column("target_cost_npr", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("target_mrp_npr", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_styles")),
        sa.UniqueConstraint("style_code", name=op.f("uq_product_styles_style_code")),
    )
    op.create_index(
        "ix_product_styles_category_status",
        "product_styles",
        ["category", "sample_status"],
        unique=False,
    )
    op.create_table(
        "roles",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("name", name=op.f("uq_roles_name")),
    )
    op.create_table(
        "suppliers",
        sa.Column("supplier_code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("contact_person", sa.String(length=160), nullable=True),
        sa.Column("phone", sa.String(length=40), nullable=True),
        sa.Column("email", sa.String(length=256), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column(
            "material_categories",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("usual_lead_time_days", sa.Integer(), nullable=True),
        sa.Column("rating", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_suppliers")),
        sa.UniqueConstraint("supplier_code", name=op.f("uq_suppliers_supplier_code")),
    )
    op.create_table(
        "task_boards",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("board_type", sa.String(length=60), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_boards")),
        sa.UniqueConstraint("name", name=op.f("uq_task_boards_name")),
    )
    op.create_table(
        "employee_skills",
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("skill", sa.String(length=80), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("fk_employee_skills_employee_id_employees"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employee_skills")),
        sa.UniqueConstraint("employee_id", "skill", name="uq_employee_skills_employee_skill"),
    )
    op.create_table(
        "materials",
        sa.Column("material_code", sa.String(length=48), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=False),
        sa.Column("unit_of_measure", sa.String(length=32), nullable=False),
        sa.Column("supplier_id", sa.UUID(), nullable=True),
        sa.Column(
            "minimum_stock", sa.Numeric(precision=14, scale=3), server_default="0", nullable=False
        ),
        sa.Column("average_cost_npr", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("last_purchase_cost_npr", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("location", sa.String(length=120), nullable=True),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
            name=op.f("fk_materials_supplier_id_suppliers"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_materials")),
        sa.UniqueConstraint("material_code", name=op.f("uq_materials_material_code")),
    )
    op.create_index(
        "ix_materials_category_active", "materials", ["category", "active"], unique=False
    )
    op.create_table(
        "product_variants",
        sa.Column("product_style_id", sa.UUID(), nullable=False),
        sa.Column("color", sa.String(length=80), nullable=False),
        sa.Column("size", sa.String(length=24), nullable=False),
        sa.Column("sku", sa.String(length=80), nullable=True),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_style_id"],
            ["product_styles.id"],
            name=op.f("fk_product_variants_product_style_id_product_styles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_variants")),
        sa.UniqueConstraint(
            "product_style_id", "color", "size", name="uq_product_variants_style_color_size"
        ),
        sa.UniqueConstraint("sku", name=op.f("uq_product_variants_sku")),
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("permission_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
            name=op.f("fk_role_permissions_permission_id_permissions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_role_permissions_role_id_roles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("role_id", "permission_id", name=op.f("pk_role_permissions")),
    )
    roles_table = sa.table(
        "roles",
        sa.column("id", sa.UUID()),
        sa.column("name", sa.String()),
        sa.column("description", sa.Text()),
    )
    permissions_table = sa.table(
        "permissions",
        sa.column("id", sa.UUID()),
        sa.column("code", sa.String()),
        sa.column("description", sa.Text()),
    )
    role_permissions_table = sa.table(
        "role_permissions",
        sa.column("role_id", sa.UUID()),
        sa.column("permission_id", sa.UUID()),
    )
    task_boards_table = sa.table(
        "task_boards",
        sa.column("id", sa.UUID()),
        sa.column("name", sa.String()),
        sa.column("board_type", sa.String()),
    )

    core_roles = [
        {
            "id": "00000000-0000-4000-8000-000000000001",
            "name": "owner_admin",
            "description": "Full system owner with bootstrap and administrative access.",
        },
        {
            "id": "00000000-0000-4000-8000-000000000002",
            "name": "factory_manager",
            "description": "Runs daily production planning, review, and reporting.",
        },
        {
            "id": "00000000-0000-4000-8000-000000000003",
            "name": "inventory_clerk",
            "description": "Manages stock counts, movements, and inventory checks.",
        },
        {
            "id": "00000000-0000-4000-8000-000000000004",
            "name": "purchasing",
            "description": "Manages suppliers, material purchase follow-up, and received stock.",
        },
        {
            "id": "00000000-0000-4000-8000-000000000005",
            "name": "hr_admin",
            "description": "Manages employee records and HR-sensitive information.",
        },
        {
            "id": "00000000-0000-4000-8000-000000000006",
            "name": "quality_inspector",
            "description": "Records quality checks, defects, and rework decisions.",
        },
        {
            "id": "00000000-0000-4000-8000-000000000007",
            "name": "sales_dispatch",
            "description": "Manages finished goods dispatch and customer handoff.",
        },
        {
            "id": "00000000-0000-4000-8000-000000000008",
            "name": "worker",
            "description": "Updates assigned factory-floor tasks.",
        },
    ]
    core_permissions = [
        {
            "id": "00000000-0000-4000-8000-000000000101",
            "code": "users.manage",
            "description": "Invite, disable, and manage app users.",
        },
        {
            "id": "00000000-0000-4000-8000-000000000102",
            "code": "employees.manage",
            "description": "Manage employee records.",
        },
        {
            "id": "00000000-0000-4000-8000-000000000103",
            "code": "tasks.manage",
            "description": "Create, assign, review, and close tasks.",
        },
        {
            "id": "00000000-0000-4000-8000-000000000104",
            "code": "tasks.update_assigned",
            "description": "Update assigned task progress from the factory floor.",
        },
        {
            "id": "00000000-0000-4000-8000-000000000105",
            "code": "inventory.manage",
            "description": "Record stock and inventory movement transactions.",
        },
        {
            "id": "00000000-0000-4000-8000-000000000106",
            "code": "purchasing.manage",
            "description": "Manage supplier and purchase follow-up workflows.",
        },
        {
            "id": "00000000-0000-4000-8000-000000000107",
            "code": "products.manage",
            "description": "Manage product styles, variants, and gallery records.",
        },
        {
            "id": "00000000-0000-4000-8000-000000000108",
            "code": "bom.manage",
            "description": "Manage BOM versions and costing inputs.",
        },
        {
            "id": "00000000-0000-4000-8000-000000000109",
            "code": "work_orders.manage",
            "description": "Plan, update, and close work orders.",
        },
        {
            "id": "00000000-0000-4000-8000-000000000110",
            "code": "qc.manage",
            "description": "Record quality inspections, defects, and rework.",
        },
        {
            "id": "00000000-0000-4000-8000-000000000111",
            "code": "labels.manage",
            "description": "Manage label templates and print jobs.",
        },
        {
            "id": "00000000-0000-4000-8000-000000000112",
            "code": "dispatch.manage",
            "description": "Manage finished goods dispatch workflows.",
        },
        {
            "id": "00000000-0000-4000-8000-000000000113",
            "code": "reports.view",
            "description": "View operational dashboards and reports.",
        },
        {
            "id": "00000000-0000-4000-8000-000000000114",
            "code": "settings.manage",
            "description": "Manage system settings and high-risk configuration.",
        },
    ]

    op.bulk_insert(roles_table, core_roles)
    op.bulk_insert(permissions_table, core_permissions)
    op.bulk_insert(
        role_permissions_table,
        [
            {
                "role_id": "00000000-0000-4000-8000-000000000001",
                "permission_id": permission["id"],
            }
            for permission in core_permissions
        ],
    )
    op.bulk_insert(
        task_boards_table,
        [
            {
                "id": "00000000-0000-4000-8000-000000000201",
                "name": "Production",
                "board_type": "production",
            },
            {
                "id": "00000000-0000-4000-8000-000000000202",
                "name": "Inventory",
                "board_type": "inventory",
            },
            {
                "id": "00000000-0000-4000-8000-000000000203",
                "name": "Quality",
                "board_type": "quality",
            },
        ],
    )
    op.create_table(
        "users",
        sa.Column("cognito_sub", sa.String(length=128), nullable=True),
        sa.Column("email", sa.String(length=256), nullable=True),
        sa.Column("phone", sa.String(length=40), nullable=True),
        sa.Column("display_name", sa.String(length=160), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=True),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column(
            "invite_status", sa.String(length=24), server_default="not_invited", nullable=False
        ),
        sa.Column("status", sa.String(length=24), server_default="active", nullable=False),
        sa.Column("invited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invited_by_user_id", sa.UUID(), nullable=True),
        sa.Column("accepted_invite_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "invite_status in ('not_invited', 'invited', 'accepted', 'disabled')",
            name=op.f("ck_users_user_invite_status"),
        ),
        sa.CheckConstraint("status in ('active', 'disabled')", name=op.f("ck_users_user_status")),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("fk_users_employee_id_employees"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["invited_by_user_id"],
            ["users.id"],
            name=op.f("fk_users_invited_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_users_role_id_roles"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(
        "ix_users_cognito_sub",
        "users",
        ["cognito_sub"],
        unique=True,
        postgresql_where=sa.text("cognito_sub is not null"),
    )
    op.create_index(
        "ix_users_email",
        "users",
        ["email"],
        unique=True,
        postgresql_where=sa.text("email is not null"),
    )
    op.create_table(
        "audit_logs",
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=120), nullable=False),
        sa.Column("entity_type", sa.String(length=120), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("before_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_logs_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(
        "ix_audit_logs_entity_created",
        "audit_logs",
        ["entity_type", "entity_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "bom_versions",
        sa.Column("product_style_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="draft", nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by_user_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_user_id"],
            ["users.id"],
            name=op.f("fk_bom_versions_approved_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["product_style_id"],
            ["product_styles.id"],
            name=op.f("fk_bom_versions_product_style_id_product_styles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bom_versions")),
        sa.UniqueConstraint("product_style_id", "version", name="uq_bom_versions_style_version"),
    )
    op.create_table(
        "inventory_stock",
        sa.Column("material_id", sa.UUID(), nullable=True),
        sa.Column("product_variant_id", sa.UUID(), nullable=True),
        sa.Column("stock_type", sa.String(length=32), nullable=False),
        sa.Column(
            "quantity", sa.Numeric(precision=14, scale=3), server_default="0", nullable=False
        ),
        sa.Column("unit_of_measure", sa.String(length=32), nullable=False),
        sa.Column("location", sa.String(length=120), nullable=True),
        sa.Column("qc_status", sa.String(length=40), nullable=True),
        sa.Column("label_status", sa.String(length=40), nullable=True),
        sa.Column("batch_no", sa.String(length=80), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(material_id is not null and product_variant_id is null) or (material_id is null and product_variant_id is not null)",
            name=op.f("ck_inventory_stock_inventory_stock_exactly_one_item"),
        ),
        sa.CheckConstraint(
            "quantity >= 0", name=op.f("ck_inventory_stock_inventory_stock_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
            name=op.f("fk_inventory_stock_material_id_materials"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_variant_id"],
            ["product_variants.id"],
            name=op.f("fk_inventory_stock_product_variant_id_product_variants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_stock")),
    )
    op.create_index(
        "ix_inventory_stock_material_id", "inventory_stock", ["material_id"], unique=False
    )
    op.create_index(
        "ix_inventory_stock_product_variant_id",
        "inventory_stock",
        ["product_variant_id"],
        unique=False,
    )
    op.create_table(
        "label_templates",
        sa.Column("template_code", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("template_type", sa.String(length=60), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="draft", nullable=False),
        sa.Column("page_width_mm", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("page_height_mm", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("label_width_mm", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("label_height_mm", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("margin_top_mm", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("margin_left_mm", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("gap_x_mm", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("gap_y_mm", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("slots_per_page", sa.Integer(), nullable=False),
        sa.Column("columns", sa.Integer(), nullable=False),
        sa.Column("rows", sa.Integer(), nullable=False),
        sa.Column("fill_order", sa.String(length=40), server_default="row_major", nullable=False),
        sa.Column(
            "offset_x_mm", sa.Numeric(precision=8, scale=2), server_default="0", nullable=False
        ),
        sa.Column(
            "offset_y_mm", sa.Numeric(precision=8, scale=2), server_default="0", nullable=False
        ),
        sa.Column(
            "design_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by_user_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "label_height_mm > 0",
            name=op.f("ck_label_templates_label_template_label_height_positive"),
        ),
        sa.CheckConstraint(
            "label_width_mm > 0",
            name=op.f("ck_label_templates_label_template_label_width_positive"),
        ),
        sa.CheckConstraint(
            "page_height_mm > 0",
            name=op.f("ck_label_templates_label_template_page_height_positive"),
        ),
        sa.CheckConstraint(
            "page_width_mm > 0", name=op.f("ck_label_templates_label_template_page_width_positive")
        ),
        sa.CheckConstraint(
            "slots_per_page > 0", name=op.f("ck_label_templates_label_template_slots_positive")
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_user_id"],
            ["users.id"],
            name=op.f("fk_label_templates_approved_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_label_templates")),
        sa.UniqueConstraint("template_code", "version", name="uq_label_templates_code_version"),
    )
    op.create_table(
        "bom_items",
        sa.Column("bom_version_id", sa.UUID(), nullable=False),
        sa.Column("material_id", sa.UUID(), nullable=False),
        sa.Column("quantity_per_pair", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column(
            "wastage_percent", sa.Numeric(precision=5, scale=2), server_default="0", nullable=False
        ),
        sa.Column("cost_snapshot_npr", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bom_version_id"],
            ["bom_versions.id"],
            name=op.f("fk_bom_items_bom_version_id_bom_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
            name=op.f("fk_bom_items_material_id_materials"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bom_items")),
    )
    op.create_table(
        "work_orders",
        sa.Column("work_order_code", sa.String(length=48), nullable=False),
        sa.Column("product_style_id", sa.UUID(), nullable=False),
        sa.Column("bom_version_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=40), server_default="draft", nullable=False),
        sa.Column("priority", sa.String(length=24), server_default="normal", nullable=False),
        sa.Column("planned_pairs", sa.Integer(), nullable=False),
        sa.Column("completed_pairs", sa.Integer(), server_default="0", nullable=False),
        sa.Column("current_stage", sa.String(length=80), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("cost_snapshot_npr", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "completed_pairs >= 0",
            name=op.f("ck_work_orders_work_order_completed_pairs_non_negative"),
        ),
        sa.CheckConstraint(
            "planned_pairs > 0", name=op.f("ck_work_orders_work_order_planned_pairs_positive")
        ),
        sa.ForeignKeyConstraint(
            ["bom_version_id"],
            ["bom_versions.id"],
            name=op.f("fk_work_orders_bom_version_id_bom_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_style_id"],
            ["product_styles.id"],
            name=op.f("fk_work_orders_product_style_id_product_styles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_work_orders")),
        sa.UniqueConstraint("work_order_code", name=op.f("uq_work_orders_work_order_code")),
    )
    op.create_index(
        "ix_work_orders_status_due_date", "work_orders", ["status", "due_date"], unique=False
    )
    op.create_table(
        "inventory_movements",
        sa.Column("movement_code", sa.String(length=48), nullable=False),
        sa.Column("stock_id", sa.UUID(), nullable=True),
        sa.Column("material_id", sa.UUID(), nullable=True),
        sa.Column("product_variant_id", sa.UUID(), nullable=True),
        sa.Column("work_order_id", sa.UUID(), nullable=True),
        sa.Column("movement_type", sa.String(length=40), nullable=False),
        sa.Column("quantity_delta", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.Column("unit_of_measure", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("performed_by_user_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
            name=op.f("fk_inventory_movements_material_id_materials"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["performed_by_user_id"],
            ["users.id"],
            name=op.f("fk_inventory_movements_performed_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["product_variant_id"],
            ["product_variants.id"],
            name=op.f("fk_inventory_movements_product_variant_id_product_variants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["stock_id"],
            ["inventory_stock.id"],
            name=op.f("fk_inventory_movements_stock_id_inventory_stock"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["work_order_id"],
            ["work_orders.id"],
            name=op.f("fk_inventory_movements_work_order_id_work_orders"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_movements")),
        sa.UniqueConstraint("movement_code", name=op.f("uq_inventory_movements_movement_code")),
    )
    op.create_index(
        "ix_inventory_movements_created_at", "inventory_movements", ["created_at"], unique=False
    )
    op.create_table(
        "label_print_jobs",
        sa.Column("print_job_code", sa.String(length=48), nullable=False),
        sa.Column("template_id", sa.UUID(), nullable=False),
        sa.Column("work_order_id", sa.UUID(), nullable=True),
        sa.Column("product_style_id", sa.UUID(), nullable=True),
        sa.Column("requested_quantity", sa.Integer(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=False),
        sa.Column(
            "field_values",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("pdf_s3_key", sa.String(length=512), nullable=True),
        sa.Column("printed_by_user_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["printed_by_user_id"],
            ["users.id"],
            name=op.f("fk_label_print_jobs_printed_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["product_style_id"],
            ["product_styles.id"],
            name=op.f("fk_label_print_jobs_product_style_id_product_styles"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["label_templates.id"],
            name=op.f("fk_label_print_jobs_template_id_label_templates"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["work_order_id"],
            ["work_orders.id"],
            name=op.f("fk_label_print_jobs_work_order_id_work_orders"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_label_print_jobs")),
        sa.UniqueConstraint("print_job_code", name=op.f("uq_label_print_jobs_print_job_code")),
    )
    op.create_index(
        "ix_label_print_jobs_created_at", "label_print_jobs", ["created_at"], unique=False
    )
    op.create_table(
        "quality_inspections",
        sa.Column("inspection_code", sa.String(length=48), nullable=False),
        sa.Column("work_order_id", sa.UUID(), nullable=True),
        sa.Column("product_style_id", sa.UUID(), nullable=True),
        sa.Column("inspected_by_user_id", sa.UUID(), nullable=True),
        sa.Column("inspected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("inspected_quantity", sa.Integer(), nullable=False),
        sa.Column("defect_quantity", sa.Integer(), server_default="0", nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "defect_quantity <= inspected_quantity",
            name=op.f("ck_quality_inspections_quality_inspection_defects_lte_inspected"),
        ),
        sa.CheckConstraint(
            "defect_quantity >= 0",
            name=op.f("ck_quality_inspections_quality_inspection_defects_non_negative"),
        ),
        sa.CheckConstraint(
            "inspected_quantity > 0",
            name=op.f("ck_quality_inspections_quality_inspection_quantity_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["inspected_by_user_id"],
            ["users.id"],
            name=op.f("fk_quality_inspections_inspected_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["product_style_id"],
            ["product_styles.id"],
            name=op.f("fk_quality_inspections_product_style_id_product_styles"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["work_order_id"],
            ["work_orders.id"],
            name=op.f("fk_quality_inspections_work_order_id_work_orders"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quality_inspections")),
        sa.UniqueConstraint("inspection_code", name=op.f("uq_quality_inspections_inspection_code")),
    )
    op.create_table(
        "tasks",
        sa.Column("task_code", sa.String(length=48), nullable=False),
        sa.Column("title", sa.String(length=220), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("board_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=40), server_default="backlog", nullable=False),
        sa.Column("priority", sa.String(length=24), server_default="normal", nullable=False),
        sa.Column("assigned_to_employee_id", sa.UUID(), nullable=True),
        sa.Column("assigned_team", sa.String(length=120), nullable=True),
        sa.Column("work_order_id", sa.UUID(), nullable=True),
        sa.Column("product_style_id", sa.UUID(), nullable=True),
        sa.Column("material_id", sa.UUID(), nullable=True),
        sa.Column("supplier_id", sa.UUID(), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("estimated_quantity", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column(
            "completed_quantity",
            sa.Numeric(precision=14, scale=3),
            server_default="0",
            nullable=False,
        ),
        sa.Column("unit_of_measure", sa.String(length=32), nullable=True),
        sa.Column("blocked_reason", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by_user_id", sa.UUID(), nullable=True),
        sa.Column("requires_review", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "completed_quantity >= 0", name=op.f("ck_tasks_task_completed_quantity_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to_employee_id"],
            ["employees.id"],
            name=op.f("fk_tasks_assigned_to_employee_id_employees"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["board_id"],
            ["task_boards.id"],
            name=op.f("fk_tasks_board_id_task_boards"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
            name=op.f("fk_tasks_material_id_materials"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["product_style_id"],
            ["product_styles.id"],
            name=op.f("fk_tasks_product_style_id_product_styles"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_user_id"],
            ["users.id"],
            name=op.f("fk_tasks_reviewed_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
            name=op.f("fk_tasks_supplier_id_suppliers"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["work_order_id"],
            ["work_orders.id"],
            name=op.f("fk_tasks_work_order_id_work_orders"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
        sa.UniqueConstraint("task_code", name=op.f("uq_tasks_task_code")),
    )
    op.create_index(
        "ix_tasks_assigned_employee_status_due",
        "tasks",
        ["assigned_to_employee_id", "status", "due_at"],
        unique=False,
    )
    op.create_index(
        "ix_tasks_board_status_priority", "tasks", ["board_id", "status", "priority"], unique=False
    )
    op.create_index("ix_tasks_status_due_at", "tasks", ["status", "due_at"], unique=False)
    op.create_index(
        "ix_tasks_work_order_status", "tasks", ["work_order_id", "status"], unique=False
    )
    op.create_table(
        "work_order_size_lines",
        sa.Column("work_order_id", sa.UUID(), nullable=False),
        sa.Column("color", sa.String(length=80), nullable=False),
        sa.Column("size", sa.String(length=24), nullable=False),
        sa.Column("planned_pairs", sa.Integer(), nullable=False),
        sa.Column("completed_pairs", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "completed_pairs >= 0",
            name=op.f("ck_work_order_size_lines_work_order_size_line_completed_pairs_non_negative"),
        ),
        sa.CheckConstraint(
            "planned_pairs > 0",
            name=op.f("ck_work_order_size_lines_work_order_size_line_planned_pairs_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["work_order_id"],
            ["work_orders.id"],
            name=op.f("fk_work_order_size_lines_work_order_id_work_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_work_order_size_lines")),
        sa.UniqueConstraint(
            "work_order_id", "color", "size", name="uq_work_order_size_lines_order_color_size"
        ),
    )
    op.create_table(
        "quality_defects",
        sa.Column("inspection_id", sa.UUID(), nullable=False),
        sa.Column("defect_type", sa.String(length=80), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("severity", sa.String(length=40), nullable=True),
        sa.Column("rework_task_id", sa.UUID(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "quantity > 0", name=op.f("ck_quality_defects_quality_defect_quantity_positive")
        ),
        sa.ForeignKeyConstraint(
            ["inspection_id"],
            ["quality_inspections.id"],
            name=op.f("fk_quality_defects_inspection_id_quality_inspections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["rework_task_id"],
            ["tasks.id"],
            name=op.f("fk_quality_defects_rework_task_id_tasks"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quality_defects")),
    )
    op.create_table(
        "task_status_updates",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("old_status", sa.String(length=40), nullable=True),
        sa.Column("new_status", sa.String(length=40), nullable=False),
        sa.Column("update_note", sa.Text(), nullable=True),
        sa.Column("blocker_reason", sa.Text(), nullable=True),
        sa.Column("completed_quantity", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_task_status_updates_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
            name=op.f("fk_task_status_updates_task_id_tasks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_status_updates")),
    )
    op.create_index(
        "ix_task_status_updates_task_created",
        "task_status_updates",
        ["task_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_task_status_updates_task_created", table_name="task_status_updates")
    op.drop_table("task_status_updates")
    op.drop_table("quality_defects")
    op.drop_table("work_order_size_lines")
    op.drop_index("ix_tasks_work_order_status", table_name="tasks")
    op.drop_index("ix_tasks_status_due_at", table_name="tasks")
    op.drop_index("ix_tasks_board_status_priority", table_name="tasks")
    op.drop_index("ix_tasks_assigned_employee_status_due", table_name="tasks")
    op.drop_table("tasks")
    op.drop_table("quality_inspections")
    op.drop_index("ix_label_print_jobs_created_at", table_name="label_print_jobs")
    op.drop_table("label_print_jobs")
    op.drop_index("ix_inventory_movements_created_at", table_name="inventory_movements")
    op.drop_table("inventory_movements")
    op.drop_index("ix_work_orders_status_due_date", table_name="work_orders")
    op.drop_table("work_orders")
    op.drop_table("bom_items")
    op.drop_table("label_templates")
    op.drop_index("ix_inventory_stock_product_variant_id", table_name="inventory_stock")
    op.drop_index("ix_inventory_stock_material_id", table_name="inventory_stock")
    op.drop_table("inventory_stock")
    op.drop_table("bom_versions")
    op.drop_index("ix_audit_logs_entity_created", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(
        "ix_users_email", table_name="users", postgresql_where=sa.text("email is not null")
    )
    op.drop_index(
        "ix_users_cognito_sub",
        table_name="users",
        postgresql_where=sa.text("cognito_sub is not null"),
    )
    op.drop_table("users")
    op.drop_table("role_permissions")
    op.drop_table("product_variants")
    op.drop_index("ix_materials_category_active", table_name="materials")
    op.drop_table("materials")
    op.drop_table("employee_skills")
    op.drop_table("task_boards")
    op.drop_table("suppliers")
    op.drop_table("roles")
    op.drop_index("ix_product_styles_category_status", table_name="product_styles")
    op.drop_table("product_styles")
    op.drop_table("permissions")
    op.drop_index("ix_employees_status_department", table_name="employees")
    op.drop_table("employees")
    # ### end Alembic commands ###
