"""add task comments

Revision ID: 97e55c766e03
Revises: 6316720c4c8c
Create Date: 2026-05-02 21:00:15.812006+00:00

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "97e55c766e03"
down_revision: str | None = "6316720c4c8c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TASK_COMMENT_PERMISSION_ID = "00000000-0000-4000-8000-000000000115"
CORE_ROLE_IDS = [
    "00000000-0000-4000-8000-000000000001",
    "00000000-0000-4000-8000-000000000002",
    "00000000-0000-4000-8000-000000000003",
    "00000000-0000-4000-8000-000000000004",
    "00000000-0000-4000-8000-000000000005",
    "00000000-0000-4000-8000-000000000006",
    "00000000-0000-4000-8000-000000000007",
    "00000000-0000-4000-8000-000000000008",
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    permissions_table = sa.table(
        "permissions",
        sa.column("id", sa.UUID()),
        sa.column("code", sa.String()),
        sa.column("description", sa.Text()),
    )
    role_permissions_table = sa.table(
        "role_permissions",
        sa.column("role_id", sa.UUID()),
        sa.column("permission_id", sa.UUID()),
    )

    op.bulk_insert(
        permissions_table,
        [
            {
                "id": TASK_COMMENT_PERMISSION_ID,
                "code": "tasks.comment",
                "description": "Add comments to visible tasks and edit owned comments.",
            }
        ],
    )
    op.bulk_insert(
        role_permissions_table,
        [
            {"role_id": role_id, "permission_id": TASK_COMMENT_PERMISSION_ID}
            for role_id in CORE_ROLE_IDS
        ],
    )

    op.add_column("tasks", sa.Column("assigned_to_user_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        op.f("fk_tasks_assigned_to_user_id_users"),
        "tasks",
        "users",
        ["assigned_to_user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_index(
        "ix_tasks_assigned_user_status_due",
        "tasks",
        ["assigned_to_user_id", "status", "due_at"],
        unique=False,
    )

    op.create_table(
        "task_comments",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("author_user_id", sa.UUID(), nullable=False),
        sa.Column("comment_text", sa.Text(), nullable=False),
        sa.Column("client_message_id", sa.String(length=80), nullable=True),
        sa.Column("edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(btrim(comment_text)) > 0",
            name=op.f("ck_task_comments_task_comment_text_not_blank"),
        ),
        sa.ForeignKeyConstraint(
            ["author_user_id"],
            ["users.id"],
            name=op.f("fk_task_comments_author_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
            name=op.f("fk_task_comments_task_id_tasks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_comments")),
        sa.UniqueConstraint(
            "author_user_id",
            "client_message_id",
            name="uq_task_comments_author_client_message",
        ),
    )
    op.create_index(
        "ix_task_comments_author_created",
        "task_comments",
        ["author_user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_task_comments_task_created",
        "task_comments",
        ["task_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    role_permissions_table = sa.table(
        "role_permissions",
        sa.column("permission_id", sa.UUID()),
    )
    permissions_table = sa.table(
        "permissions",
        sa.column("id", sa.UUID()),
    )

    op.drop_index("ix_task_comments_task_created", table_name="task_comments")
    op.drop_index("ix_task_comments_author_created", table_name="task_comments")
    op.drop_table("task_comments")
    op.drop_index("ix_tasks_assigned_user_status_due", table_name="tasks")
    op.drop_constraint(op.f("fk_tasks_assigned_to_user_id_users"), "tasks", type_="foreignkey")
    op.drop_column("tasks", "assigned_to_user_id")
    op.execute(
        role_permissions_table.delete().where(
            role_permissions_table.c.permission_id == TASK_COMMENT_PERMISSION_ID
        )
    )
    op.execute(permissions_table.delete().where(permissions_table.c.id == TASK_COMMENT_PERMISSION_ID))
    # ### end Alembic commands ###
