"""seed mvp demo data

Revision ID: b8c2f4e8d901
Revises: 97e55c766e03
Create Date: 2026-05-02 22:10:00.000000+00:00

"""

from collections.abc import Sequence
from datetime import date, datetime, timezone

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = "b8c2f4e8d901"
down_revision: str | None = "97e55c766e03"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

OWNER_ROLE_ID = "00000000-0000-4000-8000-000000000001"
MANAGER_ROLE_ID = "00000000-0000-4000-8000-000000000002"
INVENTORY_ROLE_ID = "00000000-0000-4000-8000-000000000003"
QC_ROLE_ID = "00000000-0000-4000-8000-000000000006"
WORKER_ROLE_ID = "00000000-0000-4000-8000-000000000008"
PRODUCTION_BOARD_ID = "00000000-0000-4000-8000-000000000201"
INVENTORY_BOARD_ID = "00000000-0000-4000-8000-000000000202"
QUALITY_BOARD_ID = "00000000-0000-4000-8000-000000000203"

EMPLOYEE_IDS = [
    "10000000-0000-4000-8000-000000000001",
    "10000000-0000-4000-8000-000000000002",
    "10000000-0000-4000-8000-000000000003",
    "10000000-0000-4000-8000-000000000004",
    "10000000-0000-4000-8000-000000000005",
]
USER_IDS = [
    "20000000-0000-4000-8000-000000000001",
    "20000000-0000-4000-8000-000000000002",
    "20000000-0000-4000-8000-000000000003",
    "20000000-0000-4000-8000-000000000004",
    "20000000-0000-4000-8000-000000000005",
]
SUPPLIER_IDS = [
    "30000000-0000-4000-8000-000000000001",
    "30000000-0000-4000-8000-000000000002",
    "30000000-0000-4000-8000-000000000003",
]
STYLE_IDS = [
    "40000000-0000-4000-8000-000000000001",
    "40000000-0000-4000-8000-000000000002",
]
VARIANT_IDS = [
    "41000000-0000-4000-8000-000000000001",
    "41000000-0000-4000-8000-000000000002",
    "41000000-0000-4000-8000-000000000003",
]
MATERIAL_IDS = [
    "50000000-0000-4000-8000-000000000001",
    "50000000-0000-4000-8000-000000000002",
    "50000000-0000-4000-8000-000000000003",
    "50000000-0000-4000-8000-000000000004",
]
BOM_ID = "51000000-0000-4000-8000-000000000001"
BOM_ITEM_IDS = [
    "52000000-0000-4000-8000-000000000001",
    "52000000-0000-4000-8000-000000000002",
    "52000000-0000-4000-8000-000000000003",
]
WORK_ORDER_IDS = [
    "60000000-0000-4000-8000-000000000001",
    "60000000-0000-4000-8000-000000000002",
]
SIZE_LINE_IDS = [
    "61000000-0000-4000-8000-000000000001",
    "61000000-0000-4000-8000-000000000002",
    "61000000-0000-4000-8000-000000000003",
    "61000000-0000-4000-8000-000000000004",
]
STOCK_IDS = [
    "70000000-0000-4000-8000-000000000001",
    "70000000-0000-4000-8000-000000000002",
    "70000000-0000-4000-8000-000000000003",
    "70000000-0000-4000-8000-000000000004",
    "70000000-0000-4000-8000-000000000005",
]
MOVEMENT_IDS = [
    "71000000-0000-4000-8000-000000000001",
    "71000000-0000-4000-8000-000000000002",
    "71000000-0000-4000-8000-000000000003",
]
TASK_IDS = [
    "80000000-0000-4000-8000-000000000001",
    "80000000-0000-4000-8000-000000000002",
    "80000000-0000-4000-8000-000000000003",
    "80000000-0000-4000-8000-000000000004",
    "80000000-0000-4000-8000-000000000005",
    "80000000-0000-4000-8000-000000000006",
]
TASK_UPDATE_IDS = [
    "81000000-0000-4000-8000-000000000001",
    "81000000-0000-4000-8000-000000000002",
    "81000000-0000-4000-8000-000000000003",
]
TASK_COMMENT_IDS = [
    "82000000-0000-4000-8000-000000000001",
    "82000000-0000-4000-8000-000000000002",
]
QC_IDS = ["90000000-0000-4000-8000-000000000001"]
DEFECT_IDS = ["91000000-0000-4000-8000-000000000001"]
LABEL_TEMPLATE_ID = "a0000000-0000-4000-8000-000000000001"
PRINT_JOB_ID = "a1000000-0000-4000-8000-000000000001"


def upgrade() -> None:
    now = datetime(2026, 5, 2, 9, 30, tzinfo=timezone.utc)
    due_today = datetime(2026, 5, 2, 13, 0, tzinfo=timezone.utc)
    due_later = datetime(2026, 5, 2, 16, 0, tzinfo=timezone.utc)
    due_tomorrow = datetime(2026, 5, 3, 11, 30, tzinfo=timezone.utc)

    employees = sa.table(
        "employees",
        sa.column("id", sa.UUID()),
        sa.column("employee_code", sa.String()),
        sa.column("full_name", sa.String()),
        sa.column("phone", sa.String()),
        sa.column("address", sa.Text()),
        sa.column("department", sa.String()),
        sa.column("job_title", sa.String()),
        sa.column("wage_type", sa.String()),
        sa.column("wage_rate_npr", sa.Numeric()),
        sa.column("start_date", sa.Date()),
        sa.column("status", sa.String()),
        sa.column("notes", sa.Text()),
    )
    users = sa.table(
        "users",
        sa.column("id", sa.UUID()),
        sa.column("email", sa.String()),
        sa.column("phone", sa.String()),
        sa.column("display_name", sa.String()),
        sa.column("employee_id", sa.UUID()),
        sa.column("role_id", sa.UUID()),
        sa.column("invite_status", sa.String()),
        sa.column("status", sa.String()),
        sa.column("invited_at", sa.DateTime(timezone=True)),
        sa.column("accepted_invite_at", sa.DateTime(timezone=True)),
    )
    suppliers = sa.table(
        "suppliers",
        sa.column("id", sa.UUID()),
        sa.column("supplier_code", sa.String()),
        sa.column("name", sa.String()),
        sa.column("contact_person", sa.String()),
        sa.column("phone", sa.String()),
        sa.column("address", sa.Text()),
        sa.column("material_categories", postgresql.JSONB()),
        sa.column("usual_lead_time_days", sa.Integer()),
        sa.column("rating", sa.Numeric()),
        sa.column("notes", sa.Text()),
    )
    product_styles = sa.table(
        "product_styles",
        sa.column("id", sa.UUID()),
        sa.column("style_code", sa.String()),
        sa.column("name", sa.String()),
        sa.column("category", sa.String()),
        sa.column("sample_status", sa.String()),
        sa.column("target_cost_npr", sa.Numeric()),
        sa.column("target_mrp_npr", sa.Numeric()),
        sa.column("notes", sa.Text()),
    )
    product_variants = sa.table(
        "product_variants",
        sa.column("id", sa.UUID()),
        sa.column("product_style_id", sa.UUID()),
        sa.column("color", sa.String()),
        sa.column("size", sa.String()),
        sa.column("sku", sa.String()),
        sa.column("active", sa.Boolean()),
    )
    materials = sa.table(
        "materials",
        sa.column("id", sa.UUID()),
        sa.column("material_code", sa.String()),
        sa.column("name", sa.String()),
        sa.column("category", sa.String()),
        sa.column("unit_of_measure", sa.String()),
        sa.column("supplier_id", sa.UUID()),
        sa.column("minimum_stock", sa.Numeric()),
        sa.column("average_cost_npr", sa.Numeric()),
        sa.column("last_purchase_cost_npr", sa.Numeric()),
        sa.column("location", sa.String()),
        sa.column("active", sa.Boolean()),
    )
    bom_versions = sa.table(
        "bom_versions",
        sa.column("id", sa.UUID()),
        sa.column("product_style_id", sa.UUID()),
        sa.column("version", sa.Integer()),
        sa.column("status", sa.String()),
        sa.column("approved_at", sa.DateTime(timezone=True)),
        sa.column("approved_by_user_id", sa.UUID()),
    )
    bom_items = sa.table(
        "bom_items",
        sa.column("id", sa.UUID()),
        sa.column("bom_version_id", sa.UUID()),
        sa.column("material_id", sa.UUID()),
        sa.column("quantity_per_pair", sa.Numeric()),
        sa.column("wastage_percent", sa.Numeric()),
        sa.column("cost_snapshot_npr", sa.Numeric()),
    )
    work_orders = sa.table(
        "work_orders",
        sa.column("id", sa.UUID()),
        sa.column("work_order_code", sa.String()),
        sa.column("product_style_id", sa.UUID()),
        sa.column("bom_version_id", sa.UUID()),
        sa.column("status", sa.String()),
        sa.column("priority", sa.String()),
        sa.column("planned_pairs", sa.Integer()),
        sa.column("completed_pairs", sa.Integer()),
        sa.column("current_stage", sa.String()),
        sa.column("due_date", sa.Date()),
        sa.column("cost_snapshot_npr", sa.Numeric()),
        sa.column("version", sa.Integer()),
    )
    work_order_size_lines = sa.table(
        "work_order_size_lines",
        sa.column("id", sa.UUID()),
        sa.column("work_order_id", sa.UUID()),
        sa.column("color", sa.String()),
        sa.column("size", sa.String()),
        sa.column("planned_pairs", sa.Integer()),
        sa.column("completed_pairs", sa.Integer()),
    )
    inventory_stock = sa.table(
        "inventory_stock",
        sa.column("id", sa.UUID()),
        sa.column("material_id", sa.UUID()),
        sa.column("product_variant_id", sa.UUID()),
        sa.column("stock_type", sa.String()),
        sa.column("quantity", sa.Numeric()),
        sa.column("unit_of_measure", sa.String()),
        sa.column("location", sa.String()),
        sa.column("qc_status", sa.String()),
        sa.column("label_status", sa.String()),
        sa.column("batch_no", sa.String()),
    )
    inventory_movements = sa.table(
        "inventory_movements",
        sa.column("id", sa.UUID()),
        sa.column("movement_code", sa.String()),
        sa.column("stock_id", sa.UUID()),
        sa.column("material_id", sa.UUID()),
        sa.column("product_variant_id", sa.UUID()),
        sa.column("work_order_id", sa.UUID()),
        sa.column("movement_type", sa.String()),
        sa.column("quantity_delta", sa.Numeric()),
        sa.column("unit_of_measure", sa.String()),
        sa.column("reason", sa.Text()),
        sa.column("performed_by_user_id", sa.UUID()),
    )
    tasks = sa.table(
        "tasks",
        sa.column("id", sa.UUID()),
        sa.column("task_code", sa.String()),
        sa.column("title", sa.String()),
        sa.column("description", sa.Text()),
        sa.column("board_id", sa.UUID()),
        sa.column("status", sa.String()),
        sa.column("priority", sa.String()),
        sa.column("assigned_to_employee_id", sa.UUID()),
        sa.column("assigned_to_user_id", sa.UUID()),
        sa.column("assigned_team", sa.String()),
        sa.column("work_order_id", sa.UUID()),
        sa.column("product_style_id", sa.UUID()),
        sa.column("material_id", sa.UUID()),
        sa.column("supplier_id", sa.UUID()),
        sa.column("due_at", sa.DateTime(timezone=True)),
        sa.column("estimated_quantity", sa.Numeric()),
        sa.column("completed_quantity", sa.Numeric()),
        sa.column("unit_of_measure", sa.String()),
        sa.column("blocked_reason", sa.Text()),
        sa.column("started_at", sa.DateTime(timezone=True)),
        sa.column("completed_at", sa.DateTime(timezone=True)),
        sa.column("reviewed_at", sa.DateTime(timezone=True)),
        sa.column("reviewed_by_user_id", sa.UUID()),
        sa.column("requires_review", sa.Boolean()),
        sa.column("version", sa.Integer()),
    )
    task_status_updates = sa.table(
        "task_status_updates",
        sa.column("id", sa.UUID()),
        sa.column("task_id", sa.UUID()),
        sa.column("old_status", sa.String()),
        sa.column("new_status", sa.String()),
        sa.column("update_note", sa.Text()),
        sa.column("blocker_reason", sa.Text()),
        sa.column("completed_quantity", sa.Numeric()),
        sa.column("actor_user_id", sa.UUID()),
        sa.column("created_at", sa.DateTime(timezone=True)),
    )
    task_comments = sa.table(
        "task_comments",
        sa.column("id", sa.UUID()),
        sa.column("task_id", sa.UUID()),
        sa.column("author_user_id", sa.UUID()),
        sa.column("comment_text", sa.Text()),
        sa.column("client_message_id", sa.String()),
        sa.column("edited_at", sa.DateTime(timezone=True)),
        sa.column("version", sa.Integer()),
    )
    quality_inspections = sa.table(
        "quality_inspections",
        sa.column("id", sa.UUID()),
        sa.column("inspection_code", sa.String()),
        sa.column("work_order_id", sa.UUID()),
        sa.column("product_style_id", sa.UUID()),
        sa.column("inspected_by_user_id", sa.UUID()),
        sa.column("inspected_at", sa.DateTime(timezone=True)),
        sa.column("inspected_quantity", sa.Integer()),
        sa.column("defect_quantity", sa.Integer()),
        sa.column("status", sa.String()),
        sa.column("notes", sa.Text()),
    )
    quality_defects = sa.table(
        "quality_defects",
        sa.column("id", sa.UUID()),
        sa.column("inspection_id", sa.UUID()),
        sa.column("defect_type", sa.String()),
        sa.column("quantity", sa.Integer()),
        sa.column("severity", sa.String()),
        sa.column("rework_task_id", sa.UUID()),
        sa.column("notes", sa.Text()),
    )
    label_templates = sa.table(
        "label_templates",
        sa.column("id", sa.UUID()),
        sa.column("template_code", sa.String()),
        sa.column("name", sa.String()),
        sa.column("version", sa.Integer()),
        sa.column("template_type", sa.String()),
        sa.column("status", sa.String()),
        sa.column("page_width_mm", sa.Numeric()),
        sa.column("page_height_mm", sa.Numeric()),
        sa.column("label_width_mm", sa.Numeric()),
        sa.column("label_height_mm", sa.Numeric()),
        sa.column("margin_top_mm", sa.Numeric()),
        sa.column("margin_left_mm", sa.Numeric()),
        sa.column("gap_x_mm", sa.Numeric()),
        sa.column("gap_y_mm", sa.Numeric()),
        sa.column("slots_per_page", sa.Integer()),
        sa.column("columns", sa.Integer()),
        sa.column("rows", sa.Integer()),
        sa.column("fill_order", sa.String()),
        sa.column("design_json", postgresql.JSONB()),
        sa.column("approved_at", sa.DateTime(timezone=True)),
        sa.column("approved_by_user_id", sa.UUID()),
    )
    label_print_jobs = sa.table(
        "label_print_jobs",
        sa.column("id", sa.UUID()),
        sa.column("print_job_code", sa.String()),
        sa.column("template_id", sa.UUID()),
        sa.column("work_order_id", sa.UUID()),
        sa.column("product_style_id", sa.UUID()),
        sa.column("requested_quantity", sa.Integer()),
        sa.column("page_count", sa.Integer()),
        sa.column("field_values", postgresql.JSONB()),
        sa.column("pdf_s3_key", sa.String()),
        sa.column("printed_by_user_id", sa.UUID()),
    )

    op.bulk_insert(
        employees,
        [
            {
                "id": EMPLOYEE_IDS[0],
                "employee_code": "EMP-0001",
                "full_name": "Asha Gurung",
                "phone": "+977-9800000001",
                "address": "Balaju, Kathmandu",
                "department": "Management",
                "job_title": "Owner Admin",
                "wage_type": "salary",
                "wage_rate_npr": 120000,
                "start_date": date(2024, 1, 15),
                "status": "active",
                "notes": "Initial owner/admin for launch bootstrap.",
            },
            {
                "id": EMPLOYEE_IDS[1],
                "employee_code": "EMP-0002",
                "full_name": "Milan Shrestha",
                "phone": "+977-9800000002",
                "address": "Patan, Lalitpur",
                "department": "Production",
                "job_title": "Factory Manager",
                "wage_type": "salary",
                "wage_rate_npr": 85000,
                "start_date": date(2024, 3, 1),
                "status": "active",
                "notes": "Runs work orders and production review.",
            },
            {
                "id": EMPLOYEE_IDS[2],
                "employee_code": "EMP-0003",
                "full_name": "Ram BK",
                "phone": "+977-9800000003",
                "address": "Swayambhu, Kathmandu",
                "department": "Cutting",
                "job_title": "Cutting Worker",
                "wage_type": "daily",
                "wage_rate_npr": 1500,
                "start_date": date(2025, 2, 10),
                "status": "active",
                "notes": "Primary worker used by the My Tasks demo.",
            },
            {
                "id": EMPLOYEE_IDS[3],
                "employee_code": "EMP-0004",
                "full_name": "Sita Rai",
                "phone": "+977-9800000004",
                "address": "Bhaktapur",
                "department": "Quality",
                "job_title": "QC Inspector",
                "wage_type": "salary",
                "wage_rate_npr": 60000,
                "start_date": date(2025, 4, 20),
                "status": "active",
                "notes": "Records QC inspections and rework.",
            },
            {
                "id": EMPLOYEE_IDS[4],
                "employee_code": "EMP-0005",
                "full_name": "Nima Tamang",
                "phone": "+977-9800000005",
                "address": "Kirtipur",
                "department": "Inventory",
                "job_title": "Inventory Clerk",
                "wage_type": "salary",
                "wage_rate_npr": 52000,
                "start_date": date(2025, 8, 5),
                "status": "active",
                "notes": "Receives and issues materials.",
            },
        ],
    )
    op.bulk_insert(
        users,
        [
            {
                "id": USER_IDS[0],
                "email": "owner@pailoshoes.com",
                "phone": "+977-9800000001",
                "display_name": "Asha",
                "employee_id": EMPLOYEE_IDS[0],
                "role_id": OWNER_ROLE_ID,
                "invite_status": "accepted",
                "status": "active",
                "invited_at": now,
                "accepted_invite_at": now,
            },
            {
                "id": USER_IDS[1],
                "email": "milan@pailoshoes.com",
                "phone": "+977-9800000002",
                "display_name": "Milan",
                "employee_id": EMPLOYEE_IDS[1],
                "role_id": MANAGER_ROLE_ID,
                "invite_status": "accepted",
                "status": "active",
                "invited_at": now,
                "accepted_invite_at": now,
            },
            {
                "id": USER_IDS[2],
                "email": "ram.pailo@gmail.com",
                "phone": "+977-9800000003",
                "display_name": "Ram",
                "employee_id": EMPLOYEE_IDS[2],
                "role_id": WORKER_ROLE_ID,
                "invite_status": "accepted",
                "status": "active",
                "invited_at": now,
                "accepted_invite_at": now,
            },
            {
                "id": USER_IDS[3],
                "email": "sita@pailoshoes.com",
                "phone": "+977-9800000004",
                "display_name": "Sita",
                "employee_id": EMPLOYEE_IDS[3],
                "role_id": QC_ROLE_ID,
                "invite_status": "accepted",
                "status": "active",
                "invited_at": now,
                "accepted_invite_at": now,
            },
            {
                "id": USER_IDS[4],
                "email": "nima@pailoshoes.com",
                "phone": "+977-9800000005",
                "display_name": "Nima",
                "employee_id": EMPLOYEE_IDS[4],
                "role_id": INVENTORY_ROLE_ID,
                "invite_status": "accepted",
                "status": "active",
                "invited_at": now,
                "accepted_invite_at": now,
            },
        ],
    )
    op.bulk_insert(
        suppliers,
        [
            {
                "id": SUPPLIER_IDS[0],
                "supplier_code": "SUP-0001",
                "name": "Kathmandu Threads",
                "contact_person": "Bikash",
                "phone": "+977-9811111111",
                "address": "Teku, Kathmandu",
                "material_categories": ["thread", "lining"],
                "usual_lead_time_days": 2,
                "rating": 4.6,
                "notes": "Fast local supplier for thread and lining.",
            },
            {
                "id": SUPPLIER_IDS[1],
                "supplier_code": "SUP-0002",
                "name": "Birat Sole Works",
                "contact_person": "Prakash",
                "phone": "+977-9822222222",
                "address": "Biratnagar",
                "material_categories": ["outsole", "midsole"],
                "usual_lead_time_days": 5,
                "rating": 4.2,
                "notes": "TR outsole supplier; lead-time risk for size 42.",
            },
            {
                "id": SUPPLIER_IDS[2],
                "supplier_code": "SUP-0003",
                "name": "Patan Packaging",
                "contact_person": "Anju",
                "phone": "+977-9833333333",
                "address": "Lagankhel, Lalitpur",
                "material_categories": ["box", "label paper"],
                "usual_lead_time_days": 3,
                "rating": 4.4,
                "notes": "Boxes and 24-up sticker sheets.",
            },
        ],
    )
    op.bulk_insert(
        product_styles,
        [
            {
                "id": STYLE_IDS[0],
                "style_code": "PAI-2026-SNK-001",
                "name": "Pailo City Runner",
                "category": "Sneaker",
                "sample_status": "approved",
                "target_cost_npr": 900,
                "target_mrp_npr": 2499,
                "notes": "Everyday black sneaker for the first production batch.",
            },
            {
                "id": STYLE_IDS[1],
                "style_code": "PAI-2026-SCH-001",
                "name": "Pailo School Classic",
                "category": "School shoe",
                "sample_status": "approved",
                "target_cost_npr": 760,
                "target_mrp_npr": 1899,
                "notes": "White school shoe used for QC and label workflow testing.",
            },
        ],
    )
    op.bulk_insert(
        product_variants,
        [
            {
                "id": VARIANT_IDS[0],
                "product_style_id": STYLE_IDS[0],
                "color": "Black",
                "size": "40",
                "sku": "PAI-2026-SNK-001-BLK-40",
                "active": True,
            },
            {
                "id": VARIANT_IDS[1],
                "product_style_id": STYLE_IDS[0],
                "color": "Black",
                "size": "42",
                "sku": "PAI-2026-SNK-001-BLK-42",
                "active": True,
            },
            {
                "id": VARIANT_IDS[2],
                "product_style_id": STYLE_IDS[1],
                "color": "White",
                "size": "39",
                "sku": "PAI-2026-SCH-001-WHT-39",
                "active": True,
            },
        ],
    )
    op.bulk_insert(
        materials,
        [
            {
                "id": MATERIAL_IDS[0],
                "material_code": "MAT-UPP-BLK",
                "name": "Black synthetic upper",
                "category": "upper",
                "unit_of_measure": "m",
                "supplier_id": SUPPLIER_IDS[0],
                "minimum_stock": 70,
                "average_cost_npr": 185,
                "last_purchase_cost_npr": 190,
                "location": "Rack A1",
                "active": True,
            },
            {
                "id": MATERIAL_IDS[1],
                "material_code": "MAT-THR-BLK",
                "name": "Black thread",
                "category": "thread",
                "unit_of_measure": "rolls",
                "supplier_id": SUPPLIER_IDS[0],
                "minimum_stock": 8,
                "average_cost_npr": 120,
                "last_purchase_cost_npr": 130,
                "location": "Rack B2",
                "active": True,
            },
            {
                "id": MATERIAL_IDS[2],
                "material_code": "MAT-OUT-TR42",
                "name": "TR outsole size 42",
                "category": "outsole",
                "unit_of_measure": "pairs",
                "supplier_id": SUPPLIER_IDS[1],
                "minimum_stock": 40,
                "average_cost_npr": 330,
                "last_purchase_cost_npr": 345,
                "location": "Rack C4",
                "active": True,
            },
            {
                "id": MATERIAL_IDS[3],
                "material_code": "MAT-BOX-L",
                "name": "Shoe box large",
                "category": "packaging",
                "unit_of_measure": "pcs",
                "supplier_id": SUPPLIER_IDS[2],
                "minimum_stock": 100,
                "average_cost_npr": 42,
                "last_purchase_cost_npr": 45,
                "location": "Packing store",
                "active": True,
            },
        ],
    )
    op.bulk_insert(
        bom_versions,
        [
            {
                "id": BOM_ID,
                "product_style_id": STYLE_IDS[0],
                "version": 1,
                "status": "approved",
                "approved_at": now,
                "approved_by_user_id": USER_IDS[1],
            }
        ],
    )
    op.bulk_insert(
        bom_items,
        [
            {
                "id": BOM_ITEM_IDS[0],
                "bom_version_id": BOM_ID,
                "material_id": MATERIAL_IDS[0],
                "quantity_per_pair": 0.55,
                "wastage_percent": 4,
                "cost_snapshot_npr": 102,
            },
            {
                "id": BOM_ITEM_IDS[1],
                "bom_version_id": BOM_ID,
                "material_id": MATERIAL_IDS[1],
                "quantity_per_pair": 0.04,
                "wastage_percent": 2,
                "cost_snapshot_npr": 5,
            },
            {
                "id": BOM_ITEM_IDS[2],
                "bom_version_id": BOM_ID,
                "material_id": MATERIAL_IDS[2],
                "quantity_per_pair": 1,
                "wastage_percent": 3,
                "cost_snapshot_npr": 345,
            },
        ],
    )
    op.bulk_insert(
        work_orders,
        [
            {
                "id": WORK_ORDER_IDS[0],
                "work_order_code": "WO-2026-000001",
                "product_style_id": STYLE_IDS[0],
                "bom_version_id": BOM_ID,
                "status": "in_progress",
                "priority": "high",
                "planned_pairs": 120,
                "completed_pairs": 86,
                "current_stage": "Stitching",
                "due_date": date(2026, 5, 2),
                "cost_snapshot_npr": 934,
                "version": 1,
            },
            {
                "id": WORK_ORDER_IDS[1],
                "work_order_code": "WO-2026-000002",
                "product_style_id": STYLE_IDS[1],
                "bom_version_id": None,
                "status": "qc",
                "priority": "normal",
                "planned_pairs": 40,
                "completed_pairs": 32,
                "current_stage": "QC",
                "due_date": date(2026, 5, 2),
                "cost_snapshot_npr": 748,
                "version": 1,
            },
        ],
    )
    op.bulk_insert(
        work_order_size_lines,
        [
            {
                "id": SIZE_LINE_IDS[0],
                "work_order_id": WORK_ORDER_IDS[0],
                "color": "Black",
                "size": "40",
                "planned_pairs": 60,
                "completed_pairs": 44,
            },
            {
                "id": SIZE_LINE_IDS[1],
                "work_order_id": WORK_ORDER_IDS[0],
                "color": "Black",
                "size": "42",
                "planned_pairs": 60,
                "completed_pairs": 42,
            },
            {
                "id": SIZE_LINE_IDS[2],
                "work_order_id": WORK_ORDER_IDS[1],
                "color": "White",
                "size": "39",
                "planned_pairs": 20,
                "completed_pairs": 18,
            },
            {
                "id": SIZE_LINE_IDS[3],
                "work_order_id": WORK_ORDER_IDS[1],
                "color": "White",
                "size": "40",
                "planned_pairs": 20,
                "completed_pairs": 14,
            },
        ],
    )
    op.bulk_insert(
        inventory_stock,
        [
            {
                "id": STOCK_IDS[0],
                "material_id": MATERIAL_IDS[0],
                "product_variant_id": None,
                "stock_type": "raw_material",
                "quantity": 82,
                "unit_of_measure": "m",
                "location": "Rack A1",
                "qc_status": None,
                "label_status": None,
                "batch_no": None,
            },
            {
                "id": STOCK_IDS[1],
                "material_id": MATERIAL_IDS[1],
                "product_variant_id": None,
                "stock_type": "raw_material",
                "quantity": 2,
                "unit_of_measure": "rolls",
                "location": "Rack B2",
                "qc_status": None,
                "label_status": None,
                "batch_no": None,
            },
            {
                "id": STOCK_IDS[2],
                "material_id": MATERIAL_IDS[2],
                "product_variant_id": None,
                "stock_type": "raw_material",
                "quantity": 18,
                "unit_of_measure": "pairs",
                "location": "Rack C4",
                "qc_status": None,
                "label_status": None,
                "batch_no": None,
            },
            {
                "id": STOCK_IDS[3],
                "material_id": MATERIAL_IDS[3],
                "product_variant_id": None,
                "stock_type": "raw_material",
                "quantity": 62,
                "unit_of_measure": "pcs",
                "location": "Packing store",
                "qc_status": None,
                "label_status": None,
                "batch_no": None,
            },
            {
                "id": STOCK_IDS[4],
                "material_id": None,
                "product_variant_id": VARIANT_IDS[2],
                "stock_type": "finished_goods",
                "quantity": 32,
                "unit_of_measure": "pairs",
                "location": "FG Rack 1",
                "qc_status": "passed",
                "label_status": "ready_to_print",
                "batch_no": "BATCH-WO-2026-000002",
            },
        ],
    )
    op.bulk_insert(
        inventory_movements,
        [
            {
                "id": MOVEMENT_IDS[0],
                "movement_code": "MOV-2026-000001",
                "stock_id": STOCK_IDS[0],
                "material_id": MATERIAL_IDS[0],
                "product_variant_id": None,
                "work_order_id": WORK_ORDER_IDS[0],
                "movement_type": "issue_to_work_order",
                "quantity_delta": -48,
                "unit_of_measure": "m",
                "reason": "Issued black upper material to WO-2026-000001.",
                "performed_by_user_id": USER_IDS[4],
            },
            {
                "id": MOVEMENT_IDS[1],
                "movement_code": "MOV-2026-000002",
                "stock_id": STOCK_IDS[1],
                "material_id": MATERIAL_IDS[1],
                "product_variant_id": None,
                "work_order_id": WORK_ORDER_IDS[0],
                "movement_type": "issue_to_work_order",
                "quantity_delta": -6,
                "unit_of_measure": "rolls",
                "reason": "Thread issued for stitching; now below minimum.",
                "performed_by_user_id": USER_IDS[4],
            },
            {
                "id": MOVEMENT_IDS[2],
                "movement_code": "MOV-2026-000003",
                "stock_id": STOCK_IDS[4],
                "material_id": None,
                "product_variant_id": VARIANT_IDS[2],
                "work_order_id": WORK_ORDER_IDS[1],
                "movement_type": "finished_goods_receipt",
                "quantity_delta": 32,
                "unit_of_measure": "pairs",
                "reason": "QC-cleared finished goods received for label printing.",
                "performed_by_user_id": USER_IDS[3],
            },
        ],
    )
    op.bulk_insert(
        tasks,
        [
            {
                "id": TASK_IDS[0],
                "task_code": "TASK-2026-000041",
                "title": "Cut upper material for City Runner",
                "description": "Cut black upper material for size 40 and 42 lines.",
                "board_id": PRODUCTION_BOARD_ID,
                "status": "in_progress",
                "priority": "high",
                "assigned_to_employee_id": EMPLOYEE_IDS[2],
                "assigned_to_user_id": USER_IDS[2],
                "assigned_team": "Cutting",
                "work_order_id": WORK_ORDER_IDS[0],
                "product_style_id": STYLE_IDS[0],
                "material_id": MATERIAL_IDS[0],
                "supplier_id": None,
                "due_at": due_today,
                "estimated_quantity": 120,
                "completed_quantity": 86,
                "unit_of_measure": "pairs",
                "blocked_reason": None,
                "started_at": datetime(2026, 5, 2, 8, 20, tzinfo=timezone.utc),
                "completed_at": None,
                "reviewed_at": None,
                "reviewed_by_user_id": None,
                "requires_review": False,
                "version": 1,
            },
            {
                "id": TASK_IDS[1],
                "task_code": "TASK-2026-000042",
                "title": "QC inspect white school shoes",
                "description": "Inspect 40-pair batch before labels are printed.",
                "board_id": QUALITY_BOARD_ID,
                "status": "waiting_for_review",
                "priority": "high",
                "assigned_to_employee_id": EMPLOYEE_IDS[3],
                "assigned_to_user_id": USER_IDS[3],
                "assigned_team": "Quality",
                "work_order_id": WORK_ORDER_IDS[1],
                "product_style_id": STYLE_IDS[1],
                "material_id": None,
                "supplier_id": None,
                "due_at": due_today,
                "estimated_quantity": 40,
                "completed_quantity": 32,
                "unit_of_measure": "pairs",
                "blocked_reason": None,
                "started_at": datetime(2026, 5, 2, 9, 0, tzinfo=timezone.utc),
                "completed_at": None,
                "reviewed_at": None,
                "reviewed_by_user_id": None,
                "requires_review": True,
                "version": 1,
            },
            {
                "id": TASK_IDS[2],
                "task_code": "TASK-2026-000043",
                "title": "Call outsole supplier",
                "description": "Confirm size 42 outsole delivery before tomorrow batch is blocked.",
                "board_id": INVENTORY_BOARD_ID,
                "status": "blocked",
                "priority": "urgent",
                "assigned_to_employee_id": EMPLOYEE_IDS[1],
                "assigned_to_user_id": USER_IDS[1],
                "assigned_team": "Management",
                "work_order_id": WORK_ORDER_IDS[0],
                "product_style_id": STYLE_IDS[0],
                "material_id": MATERIAL_IDS[2],
                "supplier_id": SUPPLIER_IDS[1],
                "due_at": now,
                "estimated_quantity": 40,
                "completed_quantity": 0,
                "unit_of_measure": "pairs",
                "blocked_reason": "Delivery not confirmed",
                "started_at": None,
                "completed_at": None,
                "reviewed_at": None,
                "reviewed_by_user_id": None,
                "requires_review": False,
                "version": 1,
            },
            {
                "id": TASK_IDS[3],
                "task_code": "TASK-2026-000044",
                "title": "Print size 39-40 labels",
                "description": "Print Sticker 42 labels for the QC-cleared school shoe batch.",
                "board_id": PRODUCTION_BOARD_ID,
                "status": "ready",
                "priority": "medium",
                "assigned_to_employee_id": EMPLOYEE_IDS[2],
                "assigned_to_user_id": USER_IDS[2],
                "assigned_team": "Packing",
                "work_order_id": WORK_ORDER_IDS[1],
                "product_style_id": STYLE_IDS[1],
                "material_id": MATERIAL_IDS[3],
                "supplier_id": SUPPLIER_IDS[2],
                "due_at": due_later,
                "estimated_quantity": 40,
                "completed_quantity": 0,
                "unit_of_measure": "labels",
                "blocked_reason": None,
                "started_at": None,
                "completed_at": None,
                "reviewed_at": None,
                "reviewed_by_user_id": None,
                "requires_review": False,
                "version": 1,
            },
            {
                "id": TASK_IDS[4],
                "task_code": "TASK-2026-000045",
                "title": "Issue thread to stitching station",
                "description": "Issue remaining thread and create purchase follow-up if stock stays low.",
                "board_id": INVENTORY_BOARD_ID,
                "status": "ready",
                "priority": "high",
                "assigned_to_employee_id": EMPLOYEE_IDS[4],
                "assigned_to_user_id": USER_IDS[4],
                "assigned_team": "Inventory",
                "work_order_id": WORK_ORDER_IDS[0],
                "product_style_id": STYLE_IDS[0],
                "material_id": MATERIAL_IDS[1],
                "supplier_id": SUPPLIER_IDS[0],
                "due_at": due_today,
                "estimated_quantity": 8,
                "completed_quantity": 0,
                "unit_of_measure": "rolls",
                "blocked_reason": None,
                "started_at": None,
                "completed_at": None,
                "reviewed_at": None,
                "reviewed_by_user_id": None,
                "requires_review": False,
                "version": 1,
            },
            {
                "id": TASK_IDS[5],
                "task_code": "TASK-2026-000046",
                "title": "Rework glue marks on school shoe batch",
                "description": "Rework seven pairs flagged by QC for glue marks.",
                "board_id": QUALITY_BOARD_ID,
                "status": "ready",
                "priority": "high",
                "assigned_to_employee_id": EMPLOYEE_IDS[2],
                "assigned_to_user_id": USER_IDS[2],
                "assigned_team": "Finishing",
                "work_order_id": WORK_ORDER_IDS[1],
                "product_style_id": STYLE_IDS[1],
                "material_id": None,
                "supplier_id": None,
                "due_at": due_tomorrow,
                "estimated_quantity": 7,
                "completed_quantity": 0,
                "unit_of_measure": "pairs",
                "blocked_reason": None,
                "started_at": None,
                "completed_at": None,
                "reviewed_at": None,
                "reviewed_by_user_id": None,
                "requires_review": True,
                "version": 1,
            },
        ],
    )
    op.bulk_insert(
        task_status_updates,
        [
            {
                "id": TASK_UPDATE_IDS[0],
                "task_id": TASK_IDS[0],
                "old_status": "ready",
                "new_status": "in_progress",
                "update_note": "Started cutting after materials were issued.",
                "blocker_reason": None,
                "completed_quantity": 12,
                "actor_user_id": USER_IDS[2],
                "created_at": datetime(2026, 5, 2, 8, 20, tzinfo=timezone.utc),
            },
            {
                "id": TASK_UPDATE_IDS[1],
                "task_id": TASK_IDS[2],
                "old_status": "ready",
                "new_status": "blocked",
                "update_note": "Supplier has not confirmed dispatch.",
                "blocker_reason": "Delivery not confirmed",
                "completed_quantity": None,
                "actor_user_id": USER_IDS[1],
                "created_at": datetime(2026, 5, 2, 9, 15, tzinfo=timezone.utc),
            },
            {
                "id": TASK_UPDATE_IDS[2],
                "task_id": TASK_IDS[1],
                "old_status": "in_progress",
                "new_status": "waiting_for_review",
                "update_note": "Inspection complete; manager review requested before finished goods receipt.",
                "blocker_reason": None,
                "completed_quantity": 32,
                "actor_user_id": USER_IDS[3],
                "created_at": datetime(2026, 5, 2, 10, 5, tzinfo=timezone.utc),
            },
        ],
    )
    op.bulk_insert(
        task_comments,
        [
            {
                "id": TASK_COMMENT_IDS[0],
                "task_id": TASK_IDS[0],
                "author_user_id": USER_IDS[2],
                "comment_text": "Cutting is moving, but thread stock needs attention before stitching.",
                "client_message_id": "seed-ram-001",
                "edited_at": None,
                "version": 1,
            },
            {
                "id": TASK_COMMENT_IDS[1],
                "task_id": TASK_IDS[2],
                "author_user_id": USER_IDS[1],
                "comment_text": "Calling Birat Sole Works now. Need dispatch confirmation before 15:00.",
                "client_message_id": "seed-milan-001",
                "edited_at": None,
                "version": 1,
            },
        ],
    )
    op.bulk_insert(
        quality_inspections,
        [
            {
                "id": QC_IDS[0],
                "inspection_code": "QC-2026-000001",
                "work_order_id": WORK_ORDER_IDS[1],
                "product_style_id": STYLE_IDS[1],
                "inspected_by_user_id": USER_IDS[3],
                "inspected_at": datetime(2026, 5, 2, 10, 0, tzinfo=timezone.utc),
                "inspected_quantity": 40,
                "defect_quantity": 7,
                "status": "rework_required",
                "notes": "Glue marks found on seven pairs; rework task created.",
            }
        ],
    )
    op.bulk_insert(
        quality_defects,
        [
            {
                "id": DEFECT_IDS[0],
                "inspection_id": QC_IDS[0],
                "defect_type": "glue_marks",
                "quantity": 7,
                "severity": "medium",
                "rework_task_id": TASK_IDS[5],
                "notes": "Visible marks near sole attachment.",
            }
        ],
    )
    op.bulk_insert(
        label_templates,
        [
            {
                "id": LABEL_TEMPLATE_ID,
                "template_code": "STICKER-42",
                "name": "Sticker 42 24-up A4",
                "version": 1,
                "template_type": "product_label",
                "status": "approved",
                "page_width_mm": 210,
                "page_height_mm": 297,
                "label_width_mm": 63.5,
                "label_height_mm": 33.9,
                "margin_top_mm": 12.5,
                "margin_left_mm": 7.25,
                "gap_x_mm": 3.2,
                "gap_y_mm": 1.6,
                "slots_per_page": 24,
                "columns": 3,
                "rows": 8,
                "fill_order": "row_major",
                "design_json": {
                    "brand": "Pailo",
                    "fields": ["Art No.", "Colour", "Size", "MRP", "Manufactured By", "Made in Nepal"],
                    "source_reference": "Sticker 42.doc dimensions recreated as calibrated millimeter coordinates",
                },
                "approved_at": now,
                "approved_by_user_id": USER_IDS[0],
            }
        ],
    )
    op.bulk_insert(
        label_print_jobs,
        [
            {
                "id": PRINT_JOB_ID,
                "print_job_code": "LBL-2026-000001",
                "template_id": LABEL_TEMPLATE_ID,
                "work_order_id": WORK_ORDER_IDS[1],
                "product_style_id": STYLE_IDS[1],
                "requested_quantity": 24,
                "page_count": 1,
                "field_values": {
                    "art_no": "PAI-2026-SCH-001",
                    "colour": "White",
                    "size": "39",
                    "mrp_npr": "1899",
                    "manufactured_by": "Pailo Shoes",
                    "origin_text": "Made in Nepal",
                },
                "pdf_s3_key": None,
                "printed_by_user_id": USER_IDS[1],
            }
        ],
    )


def downgrade() -> None:
    tables_and_ids = [
        ("label_print_jobs", [PRINT_JOB_ID]),
        ("label_templates", [LABEL_TEMPLATE_ID]),
        ("quality_defects", DEFECT_IDS),
        ("quality_inspections", QC_IDS),
        ("task_comments", TASK_COMMENT_IDS),
        ("task_status_updates", TASK_UPDATE_IDS),
        ("tasks", TASK_IDS),
        ("inventory_movements", MOVEMENT_IDS),
        ("inventory_stock", STOCK_IDS),
        ("work_order_size_lines", SIZE_LINE_IDS),
        ("work_orders", WORK_ORDER_IDS),
        ("bom_items", BOM_ITEM_IDS),
        ("bom_versions", [BOM_ID]),
        ("materials", MATERIAL_IDS),
        ("product_variants", VARIANT_IDS),
        ("product_styles", STYLE_IDS),
        ("suppliers", SUPPLIER_IDS),
        ("users", USER_IDS),
        ("employees", EMPLOYEE_IDS),
    ]
    for table_name, row_ids in tables_and_ids:
        ids = ", ".join(f"'{row_id}'" for row_id in row_ids)
        op.execute(sa.text(f"delete from {table_name} where id in ({ids})"))